MvcNetCoreSergioAlcazar/Controllers/ManagedController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using MvcNetCoreSergioAlcazar.Models;
using MvcNetCoreSergioAlcazar.Repositories;
using System.Security.Claims;

namespace MvcNetCoreSergioAlcazar.Controllers
{
    public class ManagedController : Controller
    {
        RepositoryLibros repo;
        public ManagedController(RepositoryLibros repo)
        {
            this.repo = repo;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(string username, string password)
        {
            Usuario usuario = await this.repo.ExisteUsuario(username, password);

            if(usuario == null)
            {
                ViewData["Error"] = "Las credenciales son incorrectas";
                return View();
            }

            ClaimsIdentity identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme,
                                                        ClaimTypes.Name, ClaimTypes.Role);

            Claim claimName = new Claim(ClaimTypes.Name, usuario.Nombre);
            identity.AddClaim(claimName);
            Claim claimId = new Claim(ClaimTypes.NameIdentifier, usuario.IdUsuario.ToString());
            identity.AddClaim(claimId);
            ClaimsPrincipal userPrincipal = new ClaimsPrincipal(identity);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, userPrincipal);

            string controller = TempData["controller"].ToString();
            string action = TempData["action"].ToString();
            string id = TempData["id"].ToString();

            return RedirectToAction(action, controller
                , new { id = id });
        }

        public async Task<IActionResult> Logout()
        {
            HttpContext.Session.Remove("Carrito");
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Libros", "Libros");
        }


    }
}

MvcNetCoreSergioAlcazar/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcNetCoreSergioAlcazar.Models;
using MvcNetCoreSergioAlcazar.Repositories;
using System.Security.Claims;
using TiendaExamen.Filters;

namespace MvcNetCoreSergioAlcazar.Controllers
{
    [AuthorizeUsers]
    public class UsuariosController : Controller
    {
        private RepositoryLibros repo;
        public UsuariosController(RepositoryLibros repo)
        {
            this.repo = repo;
        }

        public async Task<IActionResult> Perfil()
        {
            int id = int.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            Usuario usuario = await this.repo.GetUsuario(id);
            return View(usuario);
        }
    }
}

MvcNetCoreSergioAlcazar/ViewComponents/MenuGenerosViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MvcNetCoreSergioAlcazar.Models;
using MvcNetCoreSergioAlcazar.Repositories;

namespace TiendaExamen.ViewComponents
{
    public class MenuGenerosViewComponent: ViewComponent
    {
        RepositoryLibros repo;
        public MenuGenerosViewComponent(RepositoryLibros repo)
        {
            this.repo = repo;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Genero> generos = await this.repo.GetGeneros();
            return View(generos);
        }
    }
}

MvcNetCoreSergioAlcazar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcNetCoreSergioAlcazar</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcNetCoreSergioAlcazar.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Biblioteca</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @await Component.InvokeAsync("MenuGeneros")
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Libros" asp-action="Libros">Libros</a>
                        </li>
                        <partial name="_MenuPartial"/>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcNetCoreSergioAlcazar - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcNetCoreSergioAlcazar/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcNetCoreSergioAlcazar</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcNetCoreSergioAlcazar.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcNetCoreSergioAlcazar/Views/Shared/_MenuPartial.cshtml
@{
    List<Libro> libros = Context.Session.GetObject<List<Libro>>("Carrito");
    if (libros == null)
    {
        libros = new List<Libro>();
    }
}

@if (libros.Count > 0)
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-controller="Libros" asp-action="Carrito">Carrito: @libros.Count</a>
    </li>
}

@if (Context.User.Identity.IsAuthenticated == true)
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-controller="Usuarios" asp-action="Perfil">Hola @Context.User.FindFirst(ClaimTypes.Name).Value</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-controller="Managed" asp-action="Logout">Cerrar Sesion</a>
    </li>
}
else
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-controller="Usuarios" asp-action="Perfil">Iniciar Sesion</a>
    </li>
}